# Generated by Django 3.0.8 on 2021-01-21 22:03

import apps.multifunc_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blank', models.FileField(upload_to=apps.multifunc_center.models.category_directory_path, verbose_name='Файлы')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.SmallIntegerField(choices=[(1, 'doc'), (2, 'student'), (3, 'teacher')])),
            ],
        ),
    ]
