# Generated by Django 3.0.8 on 2020-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_teachers', '0004_auto_20200723_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestteacher',
            name='contacts',
            field=models.CharField(max_length=1000, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='requestteacher',
            name='user_uuid',
            field=models.UUIDField(verbose_name='UUID пользователя'),
        ),
    ]
