# Generated by Django 3.0.8 on 2020-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20200716_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio1', models.BooleanField(blank=True, null=True)),
                ('radio2', models.BooleanField(blank=True, null=True)),
                ('university_out', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование вуза на момент отчисления')),
                ('year_out', models.IntegerField(blank=True, max_length=4, null=True, verbose_name='в году')),
                ('previous_doc_year', models.IntegerField(max_length=4, verbose_name='в году')),
                ('doc', models.SmallIntegerField(choices=[(1, 'аттестат о среднем (полном) общем образовании.'), (2, 'диплом о среднем профессиональном образовании.'), (3, 'диплом о начальном профессиональном образовании.'), (4, 'академическая справка или диплом о неполном высшем образовании.'), (5, 'диплом о полном высшем образовании.')], verbose_name='Предыдущий документ об образовании')),
                ('university_in', models.CharField(max_length=300, verbose_name='Наименование вуза на момент зачисления')),
                ('year_in', models.IntegerField(max_length=4, verbose_name='в году')),
                ('user_comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
    ]
