# Generated by Django 3.0.8 on 2020-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_educationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationrequest',
            name='previous_doc_year',
            field=models.IntegerField(verbose_name='в году'),
        ),
        migrations.AlterField(
            model_name='educationrequest',
            name='year_in',
            field=models.IntegerField(verbose_name='в году'),
        ),
        migrations.AlterField(
            model_name='educationrequest',
            name='year_out',
            field=models.IntegerField(blank=True, null=True, verbose_name='в году'),
        ),
    ]
