# Generated by Django 3.0.8 on 2020-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20200716_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationrequest',
            name='user_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
