# Generated by Django 3.0.8 on 2020-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20200716_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationrequest',
            name='doc',
            field=models.SmallIntegerField(choices=[(1, 'аттестат о среднем (полном) общем образовании'), (2, 'диплом о среднем профессиональном образовании'), (3, 'диплом о начальном профессиональном образовании'), (4, 'академическая справка или диплом о неполном высшем образовании'), (5, 'диплом о полном высшем образовании')], verbose_name='Предыдущий документ об образовании'),
        ),
    ]
