# Generated by Django 3.0.8 on 2021-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_students', '0004_auto_20200723_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststudent',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файлы'),
        ),
    ]
