# Generated by Django 3.0.8 on 2020-07-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststudent',
            name='user_uuid',
            field=models.UUIDField(default='cb8d8db2-6e10-4a03-8b11-abd733f619a8', verbose_name='UUID пользователя'),
        ),
    ]
