# Generated by Django 3.0.8 on 2020-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_students', '0002_requeststudent_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststudent',
            name='contacts',
            field=models.CharField(default='ФИО, тел., почта', max_length=1000, verbose_name='Контактные данные'),
        ),
    ]
